name: QA Test Checklist
description: Use this as a guide for manual QA
title: "[QA]"
labels: ["qa"]
projects: ["tattle-made/uli"]
assignees:
  - dennybrain
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Brave

  - type: checkboxes
    id: features
    attributes:
      label: Features to check
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
        - label: I love big gals
          required: true
